name: "Test Tracker"
description: "GitHub action to track test results and metadata in Pull Requests"
author: "kirinnee"
inputs:
  data:
    required: true
    description: "Test Data to Persist"
    default: "[]"
  gist_id:
    required: true
    description: "Gist ID to use as persistent store"
  github_token:
    required: true
    description: "GitHub action token with Gist Permission"
  prefix:
    required: false
    description: "Prefix for Key Storage"
  sha:
    required: false
    description: "Use this SHA instead of commit SHA"
  url:
    required: false
    description: "Use this as the repository URL instead of auto-detection"

runs:
  using: "node16"
  main: "dist/index.js"
